apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
      nodePort: 30001
