version: "3"
services:
  app:
    build: app/
    ports:
      - 5000:5000
    environment:
      DEBUG: True
      DB_URL: postgresql://test:test@db/test
    command: "bash -c '/wait-for-it.sh db:5432 -- gunicorn main:app -b 0.0.0.0:5000'"
  db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test


  

